version: "3"

networks:
  iras-net:
    external: true

services:
  explorer.fchain.com:
    container_name: explorer.iras.com
    image: hyperledger/explorer
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ../crypto-config:/tmp/crypto
    environment:
      - DATABASE_HOST=db.explorer.iras.com
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - DISCOVERY_AS_LOCALHOST=false
    command: sh -c "sleep 16&& node /opt/explorer/main.js && tail -f /dev/null"
    ports:
      - 8090:8080
    networks:
      - iras-net

  db.explorer.fchain.com:
    container_name: db.explorer.iras.com
    image: hyperledger/explorer-db
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    volumes:
      - ./createdb.sh:/docker-entrypoint-initdb.d/createdb.sh
    networks:
      - iras-net
